#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 74143-web-01 35.174.184.145:80 check
        server 74143-web-02 54.84.42.155:80 check
"
echo -e "$server_config" >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo -e "ENABLED=1" >> /etc/default/haproxy

service haproxy restart

