#!/usr/bin/env bash
# script that configures a server that is running and listening on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
