#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet. service (init) must say that nginx is not running
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
