#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and:
# display bad luck for the 4th loop iteration
# display good luck for the 8th loop iteration
# display Best School for the other iterations

i=1

while [ $i -lt 11 ]
do
	if [ "$i" == "4" ]
	then
		echo "bad luck"
	elif [ "$i" == "8" ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
